#******************************************************************************#
#*                                                                            *#
#* src/Makefile                                                               *#
#*                                                                 2019/10/07 *#
#* Copyright (C) 2018-2019 Mochi.                                             *#
#*                                                                            *#
#******************************************************************************#
#******************************************************************************#
#* 定義                                                                       *#
#******************************************************************************#
# プログラム名
PROG = mvfs

# ソースコード
SRCS  = main.c
SRCS += Fd/Fd.c
SRCS += Fn/Fn.c
SRCS += Fn/FnMain.c
SRCS += Fn/FnTask.c
SRCS += Msg/Msg.c
SRCS += Node/Node.c

# ビルドディレクトリ
BUILD_DIR   = ../../build
# リリースディレクトリ
RELEASE_DIR = $(BUILD_DIR)/release
# オブジェクトファイル生成先ディレクトリ
OBJ_DIR     = $(BUILD_DIR)/obj/$(PROG)

# Cフラグ
CFLAGS  = -ffreestanding
CFLAGS += -nostdlib
CFLAGS += -m32
CFLAGS += -fno-pic
CFLAGS += -static
CFLAGS += -masm=intel
CFLAGS += -DDEBUG_LOG_LV=3
CFLAGS += -Iinclude
CFLAGS += -I../include
CFLAGS += -I$(BUILD_DIR)/include
ifdef BASE_CFLAGS
CFLAGS += $(BASE_CFLAGS)
endif

# LDフラグ
LDFLAGS  = -Tmvfs.lds
LDFLAGS += -melf_i386
LDFLAGS += -L$(BUILD_DIR)/lib
ifdef BASE_LDFLAGS
LDFLAGS += $(BASE_LDFLAGS)
endif

# ライブラリ
LIBS  = -lmlog
LIBS += -lc
LIBS += -lMLib
LIBS += -lmk


#******************************************************************************#
# マクロ                                                                      *#
#******************************************************************************#
# オブジェクトサブディレクトリ
OBJ_SUBDIRS = $(sort $(addprefix $(OBJ_DIR)/, $(dir $(SRCS))))

# オブジェクトファイル
OBJS = $(addprefix $(OBJ_DIR)/, $(SRCS:.c=.o))

# 依存関係ファイル
DEPS = $(addprefix $(OBJ_DIR)/, $(SRCS:.c=.d))


#******************************************************************************#
#* phonyターゲット                                                            *#
#******************************************************************************#
.PHONY: all
all: $(OBJ_SUBDIRS) $(OBJS) $(RELEASE_DIR)/$(PROG) Makefile

.PHONY: clean
clean:
	-rm -rf $(RELEASE_DIR)/$(PROG)
	-rm -rf $(OBJ_DIR)


#******************************************************************************#
#* 生成規則                                                                   *#
#******************************************************************************#
# 依存関係ファイル
-include $(DEPS)

# オブジェクトサブディレクトリ生成
ifdef OBJ_SUBDIRS
$(OBJ_SUBDIRS):
	mkdir -p $@
endif

# 実行ファイル生成
$(RELEASE_DIR)/$(PROG): $(OBJS) Makefile
	$(LD) $(LDFLAGS) -o $(OBJ_DIR)/$(PROG) $(OBJS) $(LIBS)
	ln -sfr $(OBJ_DIR)/$(PROG) $@

# コンパイル
$(OBJ_DIR)/%.o: %.c Makefile
	$(CC) $(CFLAGS) -o $@ -c $< -MD -MP


#******************************************************************************#
